server:
  port: 8080

spring:
  datasource:
    # Memoria (se borra al parar). Para pr√°cticas es perfecto:
    url: jdbc:h2:mem:paisesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update         # crea/actualiza la tabla desde las entidades
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always             # ejecuta schema.sql/data.sql si existen

  h2:
    console:
      enabled: true
      path: /h2-console        # UI para inspeccionar la BD
